name: docker

on:
  schedule:
    - cron: 25 14 * * 4
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set versions env var
        run: sed -n -e 's/.*\(VZLOGGER_.*_VERSION\) \+\([0-9]\+\).*/\1=\2/p' CMakeLists.txt >> $GITHUB_ENV
      - name: Set env sha short
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: ${{ env.image_name }}:commit-${{ env.GITHUB_SHA_SHORT }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}.${{ env.VZLOGGER_MINOR_VERSION }}.${{ env.VZLOGGER_SUB_VERSION }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}.${{ env.VZLOGGER_MINOR_VERSION }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}, ${{ env.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          image_name: ${{ secrets.DOCKERHUB_USERNAME }}/vzlogger
