name: docker

# builds that should occur:
# - push to non master branch: build only linux amd64, no docker hub push
# - pr build: build all plattforms, no docker hub push
# - build on master branch: build all plattforms, docker hub push

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set versions env var
        run: sed -n -e 's/.*\(VZLOGGER_.*_VERSION\) \+\([0-9]\+\).*/\1=\2/p' CMakeLists.txt >> $GITHUB_ENV
      - name: Set env sha short
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set all plattforms
        run: echo "PLATFORMS=linux/amd64,linux/arm/v6" >> $GITHUB_ENV
        if: ${{ github.ref == 'refs/heads/master' || github.event.pull_request }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ github.ref == 'refs/heads/master' || github.event.pull_request }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.image_name }}:commit-${{ env.GITHUB_SHA_SHORT }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}.${{ env.VZLOGGER_MINOR_VERSION }}.${{ env.VZLOGGER_SUB_VERSION }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}.${{ env.VZLOGGER_MINOR_VERSION }}, ${{ env.image_name }}:${{ env.VZLOGGER_MAJOR_VERSION }}, ${{ env.image_name }}:latest
        env:
          image_name: ${{ secrets.DOCKERHUB_USERNAME }}/vzlogger
