name: Sync Upstream

on:
  schedule:
    - cron: 25 2 * * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        run: gh repo sync stefanschoof/vzlogger
        env:
          GH_TOKEN: ${{ github.token }}
